package com.moon.vip.application.student;

import com.moon.vip.model.student.StudentProfessional;

public interface StudentProfessionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_professional
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_professional
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int insert(StudentProfessional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_professional
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int insertSelective(StudentProfessional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_professional
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    StudentProfessional selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_professional
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int updateByPrimaryKeySelective(StudentProfessional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_professional
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int updateByPrimaryKey(StudentProfessional record);
}