package com.moon.vip.model.inspect;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class InspectDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.ID
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.profession_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer professionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.class_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.student_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.inspect_date
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date inspectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.inspect_status
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer inspectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.create_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.creator
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.modify_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.modify_user
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_detail.version
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.ID
     *
     * @return the value of vip_inspect_detail.ID
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.ID
     *
     * @param id the value for vip_inspect_detail.ID
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.profession_id
     *
     * @return the value of vip_inspect_detail.profession_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.profession_id
     *
     * @param professionId the value for vip_inspect_detail.profession_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setProfessionId(Integer professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.class_id
     *
     * @return the value of vip_inspect_detail.class_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.class_id
     *
     * @param classId the value for vip_inspect_detail.class_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.student_id
     *
     * @return the value of vip_inspect_detail.student_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.student_id
     *
     * @param studentId the value for vip_inspect_detail.student_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.inspect_date
     *
     * @return the value of vip_inspect_detail.inspect_date
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Date getInspectDate() {
        return inspectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.inspect_date
     *
     * @param inspectDate the value for vip_inspect_detail.inspect_date
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setInspectDate(Date inspectDate) {
        this.inspectDate = inspectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.inspect_status
     *
     * @return the value of vip_inspect_detail.inspect_status
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getInspectStatus() {
        return inspectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.inspect_status
     *
     * @param inspectStatus the value for vip_inspect_detail.inspect_status
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setInspectStatus(Integer inspectStatus) {
        this.inspectStatus = inspectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.create_time
     *
     * @return the value of vip_inspect_detail.create_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.create_time
     *
     * @param createTime the value for vip_inspect_detail.create_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.creator
     *
     * @return the value of vip_inspect_detail.creator
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.creator
     *
     * @param creator the value for vip_inspect_detail.creator
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.modify_time
     *
     * @return the value of vip_inspect_detail.modify_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.modify_time
     *
     * @param modifyTime the value for vip_inspect_detail.modify_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.modify_user
     *
     * @return the value of vip_inspect_detail.modify_user
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.modify_user
     *
     * @param modifyUser the value for vip_inspect_detail.modify_user
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_detail.version
     *
     * @return the value of vip_inspect_detail.version
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_detail.version
     *
     * @param version the value for vip_inspect_detail.version
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	@Override
	public String toString() {
		return "InspectDetail [id=" + id + ", professionId=" + professionId + ", classId=" + classId + ", studentId="
				+ studentId + ", inspectDate=" + inspectDate + ", inspectStatus=" + inspectStatus + ", createTime="
				+ createTime + ", creator=" + creator + ", modifyTime=" + modifyTime + ", modifyUser=" + modifyUser
				+ ", version=" + version + "]";
	}
}