package com.moon.vip.model.inspect;

import java.util.Date;

public class InspectYear {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.ID
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.profession_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer professionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.class_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private String inspectYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.attendance_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer attendanceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.absence_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer absenceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.leave_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer leaveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.create_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_inspect_year.version
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.ID
     *
     * @return the value of vip_inspect_year.ID
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.ID
     *
     * @param id the value for vip_inspect_year.ID
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.profession_id
     *
     * @return the value of vip_inspect_year.profession_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.profession_id
     *
     * @param professionId the value for vip_inspect_year.profession_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setProfessionId(Integer professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.class_id
     *
     * @return the value of vip_inspect_year.class_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.class_id
     *
     * @param classId the value for vip_inspect_year.class_id
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.inspect_year
     *
     * @return the value of vip_inspect_year.inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public String getInspectYear() {
        return inspectYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.inspect_year
     *
     * @param inspectYear the value for vip_inspect_year.inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setInspectYear(String inspectYear) {
        this.inspectYear = inspectYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.attendance_number
     *
     * @return the value of vip_inspect_year.attendance_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getAttendanceNumber() {
        return attendanceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.attendance_number
     *
     * @param attendanceNumber the value for vip_inspect_year.attendance_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setAttendanceNumber(Integer attendanceNumber) {
        this.attendanceNumber = attendanceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.absence_number
     *
     * @return the value of vip_inspect_year.absence_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getAbsenceNumber() {
        return absenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.absence_number
     *
     * @param absenceNumber the value for vip_inspect_year.absence_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setAbsenceNumber(Integer absenceNumber) {
        this.absenceNumber = absenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.leave_number
     *
     * @return the value of vip_inspect_year.leave_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getLeaveNumber() {
        return leaveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.leave_number
     *
     * @param leaveNumber the value for vip_inspect_year.leave_number
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setLeaveNumber(Integer leaveNumber) {
        this.leaveNumber = leaveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.create_time
     *
     * @return the value of vip_inspect_year.create_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.create_time
     *
     * @param createTime the value for vip_inspect_year.create_time
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_inspect_year.version
     *
     * @return the value of vip_inspect_year.version
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_inspect_year.version
     *
     * @param version the value for vip_inspect_year.version
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}