package com.moon.vip.model.questionnaire;

import java.util.Date;

public class Questionnaire {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.ID
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.op_pro_ids
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String opProIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.techer_code
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String techerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.investigations_number
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Integer investigationsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.investigations_date
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Date investigationsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.excellent
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Double excellent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.good
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Double good;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.medium
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Double medium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.bad
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Double bad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.question
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.solution
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String solution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.annex_address
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String annexAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.create_time
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.creator
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.modify_time
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.modify_user
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_questionnaire.version
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.ID
     *
     * @return the value of vip_questionnaire.ID
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.ID
     *
     * @param id the value for vip_questionnaire.ID
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.op_pro_ids
     *
     * @return the value of vip_questionnaire.op_pro_ids
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getOpProIds() {
        return opProIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.op_pro_ids
     *
     * @param opProIds the value for vip_questionnaire.op_pro_ids
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setOpProIds(String opProIds) {
        this.opProIds = opProIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.techer_code
     *
     * @return the value of vip_questionnaire.techer_code
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getTecherCode() {
        return techerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.techer_code
     *
     * @param techerCode the value for vip_questionnaire.techer_code
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setTecherCode(String techerCode) {
        this.techerCode = techerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.investigations_number
     *
     * @return the value of vip_questionnaire.investigations_number
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Integer getInvestigationsNumber() {
        return investigationsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.investigations_number
     *
     * @param investigationsNumber the value for vip_questionnaire.investigations_number
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setInvestigationsNumber(Integer investigationsNumber) {
        this.investigationsNumber = investigationsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.investigations_date
     *
     * @return the value of vip_questionnaire.investigations_date
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Date getInvestigationsDate() {
        return investigationsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.investigations_date
     *
     * @param investigationsDate the value for vip_questionnaire.investigations_date
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setInvestigationsDate(Date investigationsDate) {
        this.investigationsDate = investigationsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.excellent
     *
     * @return the value of vip_questionnaire.excellent
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Double getExcellent() {
        return excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.excellent
     *
     * @param excellent the value for vip_questionnaire.excellent
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setExcellent(Double excellent) {
        this.excellent = excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.good
     *
     * @return the value of vip_questionnaire.good
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Double getGood() {
        return good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.good
     *
     * @param good the value for vip_questionnaire.good
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setGood(Double good) {
        this.good = good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.medium
     *
     * @return the value of vip_questionnaire.medium
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Double getMedium() {
        return medium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.medium
     *
     * @param medium the value for vip_questionnaire.medium
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setMedium(Double medium) {
        this.medium = medium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.bad
     *
     * @return the value of vip_questionnaire.bad
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Double getBad() {
        return bad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.bad
     *
     * @param bad the value for vip_questionnaire.bad
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setBad(Double bad) {
        this.bad = bad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.question
     *
     * @return the value of vip_questionnaire.question
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.question
     *
     * @param question the value for vip_questionnaire.question
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.solution
     *
     * @return the value of vip_questionnaire.solution
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.solution
     *
     * @param solution the value for vip_questionnaire.solution
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setSolution(String solution) {
        this.solution = solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.annex_address
     *
     * @return the value of vip_questionnaire.annex_address
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getAnnexAddress() {
        return annexAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.annex_address
     *
     * @param annexAddress the value for vip_questionnaire.annex_address
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setAnnexAddress(String annexAddress) {
        this.annexAddress = annexAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.create_time
     *
     * @return the value of vip_questionnaire.create_time
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.create_time
     *
     * @param createTime the value for vip_questionnaire.create_time
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.creator
     *
     * @return the value of vip_questionnaire.creator
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.creator
     *
     * @param creator the value for vip_questionnaire.creator
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.modify_time
     *
     * @return the value of vip_questionnaire.modify_time
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.modify_time
     *
     * @param modifyTime the value for vip_questionnaire.modify_time
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.modify_user
     *
     * @return the value of vip_questionnaire.modify_user
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.modify_user
     *
     * @param modifyUser the value for vip_questionnaire.modify_user
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_questionnaire.version
     *
     * @return the value of vip_questionnaire.version
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_questionnaire.version
     *
     * @param version the value for vip_questionnaire.version
     *
     * @mbggenerated Wed Dec 23 16:01:10 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}