package com.moon.vip.application.sys;

import com.moon.vip.model.sys.CodeTable;

public interface CodeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_code_table
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_code_table
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(CodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_code_table
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(CodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_code_table
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    CodeTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_code_table
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(CodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_code_table
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(CodeTable record);
}