package com.moon.vip.model.interviews;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Interviews implements Serializable{
    /** 
	* @Fields serialVersionUID : TODO( ) 
	*/ 
	private static final long serialVersionUID = -3044383933484962045L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.ID
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.op_pro_id
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Integer opProId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.student_id
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.techer_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String techerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.Interviewer_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String interviewerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.learn_aim_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Integer learnAimCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.learn_aim_content
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String learnAimContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.suggest
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String suggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.puzzle
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String puzzle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.note
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.create_time
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.creator
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.modify_time
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.modify_user
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_interviews.version
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.ID
     *
     * @return the value of vip_interviews.ID
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date interviewTime;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.ID
     *
     * @param id the value for vip_interviews.ID
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.op_pro_id
     *
     * @return the value of vip_interviews.op_pro_id
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public Integer getOpProId() {
        return opProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.op_pro_id
     *
     * @param opProId the value for vip_interviews.op_pro_id
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setOpProId(Integer opProId) {
        this.opProId = opProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.student_id
     *
     * @return the value of vip_interviews.student_id
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.student_id
     *
     * @param studentId the value for vip_interviews.student_id
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.techer_code
     *
     * @return the value of vip_interviews.techer_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getTecherCode() {
        return techerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.techer_code
     *
     * @param techerCode the value for vip_interviews.techer_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setTecherCode(String techerCode) {
        this.techerCode = techerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.Interviewer_code
     *
     * @return the value of vip_interviews.Interviewer_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getInterviewerCode() {
        return interviewerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.Interviewer_code
     *
     * @param interviewerCode the value for vip_interviews.Interviewer_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setInterviewerCode(String interviewerCode) {
        this.interviewerCode = interviewerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.learn_aim_code
     *
     * @return the value of vip_interviews.learn_aim_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public Integer getLearnAimCode() {
        return learnAimCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.learn_aim_code
     *
     * @param learnAimCode the value for vip_interviews.learn_aim_code
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setLearnAimCode(Integer learnAimCode) {
        this.learnAimCode = learnAimCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.learn_aim_content
     *
     * @return the value of vip_interviews.learn_aim_content
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getLearnAimContent() {
        return learnAimContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.learn_aim_content
     *
     * @param learnAimContent the value for vip_interviews.learn_aim_content
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setLearnAimContent(String learnAimContent) {
        this.learnAimContent = learnAimContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.suggest
     *
     * @return the value of vip_interviews.suggest
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.suggest
     *
     * @param suggest the value for vip_interviews.suggest
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.puzzle
     *
     * @return the value of vip_interviews.puzzle
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getPuzzle() {
        return puzzle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.puzzle
     *
     * @param puzzle the value for vip_interviews.puzzle
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setPuzzle(String puzzle) {
        this.puzzle = puzzle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.note
     *
     * @return the value of vip_interviews.note
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.note
     *
     * @param note the value for vip_interviews.note
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.create_time
     *
     * @return the value of vip_interviews.create_time
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.create_time
     *
     * @param createTime the value for vip_interviews.create_time
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.creator
     *
     * @return the value of vip_interviews.creator
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.creator
     *
     * @param creator the value for vip_interviews.creator
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.modify_time
     *
     * @return the value of vip_interviews.modify_time
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.modify_time
     *
     * @param modifyTime the value for vip_interviews.modify_time
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.modify_user
     *
     * @return the value of vip_interviews.modify_user
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.modify_user
     *
     * @param modifyUser the value for vip_interviews.modify_user
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_interviews.version
     *
     * @return the value of vip_interviews.version
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_interviews.version
     *
     * @param version the value for vip_interviews.version
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	public Date getInterviewTime() {
		return interviewTime;
	}

	public void setInterviewTime(Date interviewTime) {
		this.interviewTime = interviewTime;
	}
}