package com.moon.vip.application.assignment;

import com.moon.vip.model.assignment.SchoolAssignmentMonth;

public interface SchoolAssignmentMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_month
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_month
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insert(SchoolAssignmentMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_month
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insertSelective(SchoolAssignmentMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_month
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    SchoolAssignmentMonth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_month
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKeySelective(SchoolAssignmentMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_month
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKey(SchoolAssignmentMonth record);
}