package com.moon.vip.application.sys;

import com.moon.vip.model.sys.ActionType;

public interface ActionTypeSqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_action_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_action_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(ActionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_action_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(ActionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_action_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    ActionType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_action_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(ActionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_action_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(ActionType record);
}