package com.moon.vip.application.sys;

import com.moon.vip.model.sys.EmployeeRole;

public interface EmployeeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    EmployeeRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(EmployeeRole record);
}