package com.moon.vip.application.inspect;

import com.moon.vip.model.inspect.InspectMonth;

public interface InspectMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_month
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_month
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insert(InspectMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_month
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insertSelective(InspectMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_month
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    InspectMonth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_month
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKeySelective(InspectMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_month
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKey(InspectMonth record);
}