package com.moon.vip.model.student;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class StudentProfessional {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.student_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.op_pro_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer opProId;
    
    private String professionCode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.amount_payable
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private BigDecimal amountPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.pay_method
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.payment
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.is_arrears
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String isArrears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.arrears
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private BigDecimal arrears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.is_refund
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String isRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.refund_monetary
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private BigDecimal refundMonetary;

    
    private String status;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.refund_reason
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String refundReason;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.change_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.change_reason
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String changeReason;

    
    /***备注***/
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.enter_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date enterDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.should_attendance
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer shouldAttendance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.leave_number
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer leaveNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.fact_attendance
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer factAttendance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.should_task
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer shouldTask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.fact_task
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer factTask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.end_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.certificate
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.rewards_punishments
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String rewardsPunishments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.word_mouth
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String wordMouth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.appraise
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String appraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.write_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date writeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.study_basis
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String studyBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.ID
     *
     * @return the value of vip_student_professional.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.ID
     *
     * @param id the value for vip_student_professional.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.student_id
     *
     * @return the value of vip_student_professional.student_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.student_id
     *
     * @param studentId the value for vip_student_professional.student_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.op_pro_id
     *
     * @return the value of vip_student_professional.op_pro_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getOpProId() {
        return opProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.op_pro_id
     *
     * @param opProId the value for vip_student_professional.op_pro_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setOpProId(Integer opProId) {
        this.opProId = opProId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.amount_payable
     *
     * @return the value of vip_student_class.amount_payable
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public BigDecimal getAmountPayable() {
        return amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.amount_payable
     *
     * @param amountPayable the value for vip_student_class.amount_payable
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setAmountPayable(BigDecimal amountPayable) {
        this.amountPayable = amountPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.pay_method
     *
     * @return the value of vip_student_class.pay_method
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.pay_method
     *
     * @param payMethod the value for vip_student_class.pay_method
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.payment
     *
     * @return the value of vip_student_class.payment
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.payment
     *
     * @param payment the value for vip_student_class.payment
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.is_arrears
     *
     * @return the value of vip_student_class.is_arrears
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getIsArrears() {
        return isArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.is_arrears
     *
     * @param isArrears the value for vip_student_class.is_arrears
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setIsArrears(String isArrears) {
        this.isArrears = isArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.arrears
     *
     * @return the value of vip_student_class.arrears
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public BigDecimal getArrears() {
        return arrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.arrears
     *
     * @param arrears the value for vip_student_class.arrears
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setArrears(BigDecimal arrears) {
        this.arrears = arrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.is_refund
     *
     * @return the value of vip_student_class.is_refund
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.is_refund
     *
     * @param isRefund the value for vip_student_class.is_refund
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setIsRefund(String isRefund) {
        this.isRefund = isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.refund_monetary
     *
     * @return the value of vip_student_class.refund_monetary
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public BigDecimal getRefundMonetary() {
        return refundMonetary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.refund_monetary
     *
     * @param refundMonetary the value for vip_student_class.refund_monetary
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setRefundMonetary(BigDecimal refundMonetary) {
        this.refundMonetary = refundMonetary;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.status
     *
     * @return the value of vip_student_class.status
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.status
     *
     * @param status the value for vip_student_class.status
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.refund_reason
     *
     * @return the value of vip_student_class.refund_reason
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.refund_reason
     *
     * @param refundReason the value for vip_student_class.refund_reason
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.change_time
     *
     * @return the value of vip_student_class.change_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.change_time
     *
     * @param changeTime the value for vip_student_class.change_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.change_reason
     *
     * @return the value of vip_student_class.change_reason
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getChangeReason() {
        return changeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.change_reason
     *
     * @param changeReason the value for vip_student_class.change_reason
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.enter_date
     *
     * @return the value of vip_student_professional.enter_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.enter_date
     *
     * @param enterDate the value for vip_student_professional.enter_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.should_attendance
     *
     * @return the value of vip_student_professional.should_attendance
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getShouldAttendance() {
        return shouldAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.should_attendance
     *
     * @param shouldAttendance the value for vip_student_professional.should_attendance
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setShouldAttendance(Integer shouldAttendance) {
        this.shouldAttendance = shouldAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.leave_number
     *
     * @return the value of vip_student_professional.leave_number
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getLeaveNumber() {
        return leaveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.leave_number
     *
     * @param leaveNumber the value for vip_student_professional.leave_number
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setLeaveNumber(Integer leaveNumber) {
        this.leaveNumber = leaveNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.fact_attendance
     *
     * @return the value of vip_student_professional.fact_attendance
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getFactAttendance() {
        return factAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.fact_attendance
     *
     * @param factAttendance the value for vip_student_professional.fact_attendance
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setFactAttendance(Integer factAttendance) {
        this.factAttendance = factAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.should_task
     *
     * @return the value of vip_student_professional.should_task
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getShouldTask() {
        return shouldTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.should_task
     *
     * @param shouldTask the value for vip_student_professional.should_task
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setShouldTask(Integer shouldTask) {
        this.shouldTask = shouldTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.fact_task
     *
     * @return the value of vip_student_professional.fact_task
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getFactTask() {
        return factTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.fact_task
     *
     * @param factTask the value for vip_student_professional.fact_task
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setFactTask(Integer factTask) {
        this.factTask = factTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.end_date
     *
     * @return the value of vip_student_professional.end_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.end_date
     *
     * @param endDate the value for vip_student_professional.end_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.certificate
     *
     * @return the value of vip_student_professional.certificate
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.certificate
     *
     * @param certificate the value for vip_student_professional.certificate
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.rewards_punishments
     *
     * @return the value of vip_student_professional.rewards_punishments
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getRewardsPunishments() {
        return rewardsPunishments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.rewards_punishments
     *
     * @param rewardsPunishments the value for vip_student_professional.rewards_punishments
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setRewardsPunishments(String rewardsPunishments) {
        this.rewardsPunishments = rewardsPunishments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.word_mouth
     *
     * @return the value of vip_student_professional.word_mouth
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getWordMouth() {
        return wordMouth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.word_mouth
     *
     * @param wordMouth the value for vip_student_professional.word_mouth
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setWordMouth(String wordMouth) {
        this.wordMouth = wordMouth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.appraise
     *
     * @return the value of vip_student_professional.appraise
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getAppraise() {
        return appraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.appraise
     *
     * @param appraise the value for vip_student_professional.appraise
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setAppraise(String appraise) {
        this.appraise = appraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.write_date
     *
     * @return the value of vip_student_professional.write_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.write_date
     *
     * @param writeDate the value for vip_student_professional.write_date
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.is_valid
     *
     * @return the value of vip_student_professional.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.is_valid
     *
     * @param isValid the value for vip_student_professional.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.study_basis
     *
     * @return the value of vip_student_professional.study_basis
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getStudyBasis() {
        return studyBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.study_basis
     *
     * @param studyBasis the value for vip_student_professional.study_basis
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStudyBasis(String studyBasis) {
        this.studyBasis = studyBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.create_time
     *
     * @return the value of vip_student_professional.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.create_time
     *
     * @param createTime the value for vip_student_professional.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.creator
     *
     * @return the value of vip_student_professional.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.creator
     *
     * @param creator the value for vip_student_professional.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.modify_time
     *
     * @return the value of vip_student_professional.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.modify_time
     *
     * @param modifyTime the value for vip_student_professional.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.modify_user
     *
     * @return the value of vip_student_professional.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.modify_user
     *
     * @param modifyUser the value for vip_student_professional.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional.version
     *
     * @return the value of vip_student_professional.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional.version
     *
     * @param version the value for vip_student_professional.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "StudentProfessional [id=" + id + ", studentId=" + studentId + ", opProId=" + opProId
				+ ", professionCode=" + professionCode + ", amountPayable=" + amountPayable + ", payMethod="
				+ payMethod + ", payment=" + payment + ", isArrears=" + isArrears + ", arrears=" + arrears
				+ ", isRefund=" + isRefund + ", refundMonetary=" + refundMonetary + ", refundReason=" + refundReason
				+ ", remark=" + remark + ", enterDate=" + enterDate + ", shouldAttendance=" + shouldAttendance
				+ ", leaveNumber=" + leaveNumber + ", factAttendance=" + factAttendance + ", shouldTask=" + shouldTask
				+ ", factTask=" + factTask + ", endDate=" + endDate + ", certificate=" + certificate
				+ ", rewardsPunishments=" + rewardsPunishments + ", wordMouth=" + wordMouth + ", appraise=" + appraise
				+ ", writeDate=" + writeDate + ", isValid=" + isValid + ", studyBasis=" + studyBasis + ", createTime="
				+ createTime + ", creator=" + creator + ", modifyTime=" + modifyTime + ", modifyUser=" + modifyUser
				+ ", version=" + version + "]";
	}

	public String getProfessionCode() {
		return professionCode;
	}

	public void setProfessionCode(String professionCode) {
		this.professionCode = professionCode;
	}
}