package com.moon.vip.application.student;

import com.moon.vip.model.student.StudentArchives;

public interface StudentArchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_archives
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_archives
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int insert(StudentArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_archives
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int insertSelective(StudentArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_archives
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    StudentArchives selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_archives
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int updateByPrimaryKeySelective(StudentArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_archives
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int updateByPrimaryKey(StudentArchives record);
}