package com.moon.vip.application.sys;

import com.moon.vip.model.sys.OPManager;

public interface OPManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_OP_manager
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_OP_manager
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(OPManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_OP_manager
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(OPManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_OP_manager
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    OPManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_OP_manager
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(OPManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_OP_manager
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(OPManager record);
}