package com.moon.vip.application.sys;

import com.moon.vip.model.sys.ProfessionSequence;
import com.moon.vip.model.sys.ProfessionSequenceKey;

public interface ProfessionSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_profession_sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    int deleteByPrimaryKey(ProfessionSequenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_profession_sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    int insert(ProfessionSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_profession_sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    int insertSelective(ProfessionSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_profession_sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    ProfessionSequence selectByPrimaryKey(ProfessionSequenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_profession_sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    int updateByPrimaryKeySelective(ProfessionSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_profession_sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    int updateByPrimaryKey(ProfessionSequence record);
}