package com.moon.vip.application.inspect;

import com.moon.vip.model.inspect.InspectWeek;

public interface InspectWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_week
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_week
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insert(InspectWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_week
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insertSelective(InspectWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_week
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    InspectWeek selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_week
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKeySelective(InspectWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_week
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKey(InspectWeek record);
}