package com.moon.vip.model.sys;

import java.util.Date;

public class OPLeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.op_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer opId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.employee_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String employeeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.modify_user
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_OP_leader.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.ID
     *
     * @return the value of vip_OP_leader.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.ID
     *
     * @param id the value for vip_OP_leader.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.op_id
     *
     * @return the value of vip_OP_leader.op_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.op_id
     *
     * @param opId the value for vip_OP_leader.op_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setOpId(Integer opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.role
     *
     * @return the value of vip_OP_leader.role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.role
     *
     * @param role the value for vip_OP_leader.role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.employee_code
     *
     * @return the value of vip_OP_leader.employee_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.employee_code
     *
     * @param employeeCode the value for vip_OP_leader.employee_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.create_time
     *
     * @return the value of vip_OP_leader.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.create_time
     *
     * @param createTime the value for vip_OP_leader.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.creator
     *
     * @return the value of vip_OP_leader.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.creator
     *
     * @param creator the value for vip_OP_leader.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.modify_time
     *
     * @return the value of vip_OP_leader.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.modify_time
     *
     * @param modifyTime the value for vip_OP_leader.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.modify_user
     *
     * @return the value of vip_OP_leader.modify_user
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.modify_user
     *
     * @param modifyUser the value for vip_OP_leader.modify_user
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_OP_leader.version
     *
     * @return the value of vip_OP_leader.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_OP_leader.version
     *
     * @param version the value for vip_OP_leader.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}