package com.moon.vip.application.assignment;

import com.moon.vip.model.assignment.SchoolAssignmentYear;

public interface SchoolAssignmentYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insert(SchoolAssignmentYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insertSelective(SchoolAssignmentYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    SchoolAssignmentYear selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKeySelective(SchoolAssignmentYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKey(SchoolAssignmentYear record);
}