package com.moon.vip.application.inspect;

import com.moon.vip.model.inspect.InspectDetail;

public interface InspectDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_detail
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_detail
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insert(InspectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_detail
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insertSelective(InspectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_detail
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    InspectDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_detail
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKeySelective(InspectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_detail
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKey(InspectDetail record);
}