package com.moon.vip.model.sys;

import java.util.Date;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.role_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.menu_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role_menu.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.ID
     *
     * @return the value of vip_role_menu.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.ID
     *
     * @param id the value for vip_role_menu.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.role_id
     *
     * @return the value of vip_role_menu.role_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.role_id
     *
     * @param roleId the value for vip_role_menu.role_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.menu_id
     *
     * @return the value of vip_role_menu.menu_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.menu_id
     *
     * @param menuId the value for vip_role_menu.menu_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.create_time
     *
     * @return the value of vip_role_menu.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.create_time
     *
     * @param createTime the value for vip_role_menu.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.creator
     *
     * @return the value of vip_role_menu.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.creator
     *
     * @param creator the value for vip_role_menu.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.update_time
     *
     * @return the value of vip_role_menu.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.update_time
     *
     * @param updateTime the value for vip_role_menu.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.updator
     *
     * @return the value of vip_role_menu.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.updator
     *
     * @param updator the value for vip_role_menu.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role_menu.version
     *
     * @return the value of vip_role_menu.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role_menu.version
     *
     * @param version the value for vip_role_menu.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	@Override
	public String toString() {
		return "RoleMenu [id=" + id + ", roleId=" + roleId + ", menuId=" + menuId + ", createTime=" + createTime
				+ ", creator=" + creator + ", updateTime=" + updateTime + ", updator=" + updator + ", version="
				+ version + "]";
	}
}