package com.moon.vip.application.student;

import com.moon.vip.model.student.StudentClass;

public interface StudentClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_class
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_class
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int insert(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_class
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int insertSelective(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_class
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    StudentClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_class
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int updateByPrimaryKeySelective(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_student_class
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    int updateByPrimaryKey(StudentClass record);
}