package com.moon.vip.model.student;

import java.util.Date;

public class StudentClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.op_pro_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer opProId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.op_cla_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer opClaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.student_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.status
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.remark
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.score
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_class.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.ID
     *
     * @return the value of vip_student_class.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.ID
     *
     * @param id the value for vip_student_class.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.op_pro_id
     *
     * @return the value of vip_student_class.op_pro_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getOpProId() {
        return opProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.op_pro_id
     *
     * @param opProId the value for vip_student_class.op_pro_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setOpProId(Integer opProId) {
        this.opProId = opProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.op_cla_id
     *
     * @return the value of vip_student_class.op_cla_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getOpClaId() {
        return opClaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.op_cla_id
     *
     * @param opClaId the value for vip_student_class.op_cla_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setOpClaId(Integer opClaId) {
        this.opClaId = opClaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.student_id
     *
     * @return the value of vip_student_class.student_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.student_id
     *
     * @param studentId the value for vip_student_class.student_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.status
     *
     * @return the value of vip_student_class.status
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.status
     *
     * @param status the value for vip_student_class.status
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.is_valid
     *
     * @return the value of vip_student_class.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.is_valid
     *
     * @param isValid the value for vip_student_class.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.remark
     *
     * @return the value of vip_student_class.remark
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.remark
     *
     * @param remark the value for vip_student_class.remark
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.score
     *
     * @return the value of vip_student_class.score
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.score
     *
     * @param score the value for vip_student_class.score
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.create_time
     *
     * @return the value of vip_student_class.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.create_time
     *
     * @param createTime the value for vip_student_class.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.creator
     *
     * @return the value of vip_student_class.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.creator
     *
     * @param creator the value for vip_student_class.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.modify_time
     *
     * @return the value of vip_student_class.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.modify_time
     *
     * @param modifyTime the value for vip_student_class.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.modify_user
     *
     * @return the value of vip_student_class.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.modify_user
     *
     * @param modifyUser the value for vip_student_class.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_class.version
     *
     * @return the value of vip_student_class.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_class.version
     *
     * @param version the value for vip_student_class.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}