package com.moon.vip.model.student;

import java.util.Date;

public class StudentArchives {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.code_no
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String codeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.name
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.name_spell
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String nameSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.nick_name
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.stu_picture_url
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String stuPictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.sex
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.birthday
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.telephone
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.email
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.postal_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.QQ
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.YY
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String yy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.id_card
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.card_front_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String cardFrontAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.card_reverse_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String cardReverseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.education_background
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String educationBackground;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.emergency_person
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String emergencyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.contrat_relationships_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String contratRelationshipsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.emergency_telephone
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String emergencyTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.note
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.component_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String componentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.occupation_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String occupationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.school
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.native_place
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.hobbies
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String hobbies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.student_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String studentResources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.other_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String otherResources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.cost_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String costResources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_archives.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.ID
     *
     * @return the value of vip_student_archives.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.ID
     *
     * @param id the value for vip_student_archives.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.code_no
     *
     * @return the value of vip_student_archives.code_no
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCodeNo() {
        return codeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.code_no
     *
     * @param codeNo the value for vip_student_archives.code_no
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCodeNo(String codeNo) {
        this.codeNo = codeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.name
     *
     * @return the value of vip_student_archives.name
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.name
     *
     * @param name the value for vip_student_archives.name
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.name_spell
     *
     * @return the value of vip_student_archives.name_spell
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getNameSpell() {
        return nameSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.name_spell
     *
     * @param nameSpell the value for vip_student_archives.name_spell
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setNameSpell(String nameSpell) {
        this.nameSpell = nameSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.nick_name
     *
     * @return the value of vip_student_archives.nick_name
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.nick_name
     *
     * @param nickName the value for vip_student_archives.nick_name
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.stu_picture_url
     *
     * @return the value of vip_student_archives.stu_picture_url
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getStuPictureUrl() {
        return stuPictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.stu_picture_url
     *
     * @param stuPictureUrl the value for vip_student_archives.stu_picture_url
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStuPictureUrl(String stuPictureUrl) {
        this.stuPictureUrl = stuPictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.sex
     *
     * @return the value of vip_student_archives.sex
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.sex
     *
     * @param sex the value for vip_student_archives.sex
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.birthday
     *
     * @return the value of vip_student_archives.birthday
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.birthday
     *
     * @param birthday the value for vip_student_archives.birthday
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.telephone
     *
     * @return the value of vip_student_archives.telephone
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.telephone
     *
     * @param telephone the value for vip_student_archives.telephone
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.email
     *
     * @return the value of vip_student_archives.email
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.email
     *
     * @param email the value for vip_student_archives.email
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.postal_code
     *
     * @return the value of vip_student_archives.postal_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.postal_code
     *
     * @param postalCode the value for vip_student_archives.postal_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.QQ
     *
     * @return the value of vip_student_archives.QQ
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.QQ
     *
     * @param qq the value for vip_student_archives.QQ
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.YY
     *
     * @return the value of vip_student_archives.YY
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getYy() {
        return yy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.YY
     *
     * @param yy the value for vip_student_archives.YY
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setYy(String yy) {
        this.yy = yy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.id_card
     *
     * @return the value of vip_student_archives.id_card
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.id_card
     *
     * @param idCard the value for vip_student_archives.id_card
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.card_front_address
     *
     * @return the value of vip_student_archives.card_front_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCardFrontAddress() {
        return cardFrontAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.card_front_address
     *
     * @param cardFrontAddress the value for vip_student_archives.card_front_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCardFrontAddress(String cardFrontAddress) {
        this.cardFrontAddress = cardFrontAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.card_reverse_address
     *
     * @return the value of vip_student_archives.card_reverse_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCardReverseAddress() {
        return cardReverseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.card_reverse_address
     *
     * @param cardReverseAddress the value for vip_student_archives.card_reverse_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCardReverseAddress(String cardReverseAddress) {
        this.cardReverseAddress = cardReverseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.education_background
     *
     * @return the value of vip_student_archives.education_background
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getEducationBackground() {
        return educationBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.education_background
     *
     * @param educationBackground the value for vip_student_archives.education_background
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setEducationBackground(String educationBackground) {
        this.educationBackground = educationBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.emergency_person
     *
     * @return the value of vip_student_archives.emergency_person
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getEmergencyPerson() {
        return emergencyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.emergency_person
     *
     * @param emergencyPerson the value for vip_student_archives.emergency_person
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setEmergencyPerson(String emergencyPerson) {
        this.emergencyPerson = emergencyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.contrat_relationships_code
     *
     * @return the value of vip_student_archives.contrat_relationships_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getContratRelationshipsCode() {
        return contratRelationshipsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.contrat_relationships_code
     *
     * @param contratRelationshipsCode the value for vip_student_archives.contrat_relationships_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setContratRelationshipsCode(String contratRelationshipsCode) {
        this.contratRelationshipsCode = contratRelationshipsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.emergency_telephone
     *
     * @return the value of vip_student_archives.emergency_telephone
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getEmergencyTelephone() {
        return emergencyTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.emergency_telephone
     *
     * @param emergencyTelephone the value for vip_student_archives.emergency_telephone
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setEmergencyTelephone(String emergencyTelephone) {
        this.emergencyTelephone = emergencyTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.note
     *
     * @return the value of vip_student_archives.note
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.note
     *
     * @param note the value for vip_student_archives.note
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.is_valid
     *
     * @return the value of vip_student_archives.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.is_valid
     *
     * @param isValid the value for vip_student_archives.is_valid
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.component_code
     *
     * @return the value of vip_student_archives.component_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getComponentCode() {
        return componentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.component_code
     *
     * @param componentCode the value for vip_student_archives.component_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setComponentCode(String componentCode) {
        this.componentCode = componentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.occupation_code
     *
     * @return the value of vip_student_archives.occupation_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getOccupationCode() {
        return occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.occupation_code
     *
     * @param occupationCode the value for vip_student_archives.occupation_code
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setOccupationCode(String occupationCode) {
        this.occupationCode = occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.school
     *
     * @return the value of vip_student_archives.school
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.school
     *
     * @param school the value for vip_student_archives.school
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.native_place
     *
     * @return the value of vip_student_archives.native_place
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.native_place
     *
     * @param nativePlace the value for vip_student_archives.native_place
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.address
     *
     * @return the value of vip_student_archives.address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.address
     *
     * @param address the value for vip_student_archives.address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.hobbies
     *
     * @return the value of vip_student_archives.hobbies
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getHobbies() {
        return hobbies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.hobbies
     *
     * @param hobbies the value for vip_student_archives.hobbies
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.student_resources
     *
     * @return the value of vip_student_archives.student_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getStudentResources() {
        return studentResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.student_resources
     *
     * @param studentResources the value for vip_student_archives.student_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setStudentResources(String studentResources) {
        this.studentResources = studentResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.other_resources
     *
     * @return the value of vip_student_archives.other_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getOtherResources() {
        return otherResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.other_resources
     *
     * @param otherResources the value for vip_student_archives.other_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setOtherResources(String otherResources) {
        this.otherResources = otherResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.cost_resources
     *
     * @return the value of vip_student_archives.cost_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCostResources() {
        return costResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.cost_resources
     *
     * @param costResources the value for vip_student_archives.cost_resources
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCostResources(String costResources) {
        this.costResources = costResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.create_time
     *
     * @return the value of vip_student_archives.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.create_time
     *
     * @param createTime the value for vip_student_archives.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.creator
     *
     * @return the value of vip_student_archives.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.creator
     *
     * @param creator the value for vip_student_archives.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.modify_time
     *
     * @return the value of vip_student_archives.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.modify_time
     *
     * @param modifyTime the value for vip_student_archives.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.modify_user
     *
     * @return the value of vip_student_archives.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.modify_user
     *
     * @param modifyUser the value for vip_student_archives.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_archives.version
     *
     * @return the value of vip_student_archives.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_archives.version
     *
     * @param version the value for vip_student_archives.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	@Override
	public String toString() {
		return "StudentArchives [id=" + id + ", codeNo=" + codeNo + ", name=" + name + ", nameSpell=" + nameSpell
				+ ", nickName=" + nickName + ", stuPictureUrl=" + stuPictureUrl + ", sex=" + sex + ", birthday="
				+ birthday + ", telephone=" + telephone + ", email=" + email + ", postalCode=" + postalCode + ", qq="
				+ qq + ", yy=" + yy + ", idCard=" + idCard + ", cardFrontAddress=" + cardFrontAddress
				+ ", cardReverseAddress=" + cardReverseAddress + ", educationBackground=" + educationBackground
				+ ", emergencyPerson=" + emergencyPerson + ", contratRelationshipsCode=" + contratRelationshipsCode
				+ ", emergencyTelephone=" + emergencyTelephone + ", note=" + note + ", isValid=" + isValid
				+ ", componentCode=" + componentCode + ", occupationCode=" + occupationCode + ", school=" + school
				+ ", nativePlace=" + nativePlace + ", address=" + address + ", hobbies=" + hobbies
				+ ", studentResources=" + studentResources + ", otherResources=" + otherResources + ", costResources="
				+ costResources + ", createTime=" + createTime + ", creator=" + creator + ", modifyTime=" + modifyTime
				+ ", modifyUser=" + modifyUser + ", version=" + version + "]";
	}
    
    
}