package com.moon.vip.model.student;

import java.util.Date;

public class StudentProfessionalAttach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.sp_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer spId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.type
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.url_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    
    private String name;
    
    private String urlAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_student_professional_attach.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.ID
     *
     * @return the value of vip_student_professional_attach.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.ID
     *
     * @param id the value for vip_student_professional_attach.ID
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.sp_id
     *
     * @return the value of vip_student_professional_attach.sp_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.sp_id
     *
     * @param spId the value for vip_student_professional_attach.sp_id
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.type
     *
     * @return the value of vip_student_professional_attach.type
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.type
     *
     * @param type the value for vip_student_professional_attach.type
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.url_address
     *
     * @return the value of vip_student_professional_attach.url_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getUrlAddress() {
        return urlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.url_address
     *
     * @param urlAddress the value for vip_student_professional_attach.url_address
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setUrlAddress(String urlAddress) {
        this.urlAddress = urlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.create_time
     *
     * @return the value of vip_student_professional_attach.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.create_time
     *
     * @param createTime the value for vip_student_professional_attach.create_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.creator
     *
     * @return the value of vip_student_professional_attach.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.creator
     *
     * @param creator the value for vip_student_professional_attach.creator
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.modify_time
     *
     * @return the value of vip_student_professional_attach.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.modify_time
     *
     * @param modifyTime the value for vip_student_professional_attach.modify_time
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.modify_user
     *
     * @return the value of vip_student_professional_attach.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.modify_user
     *
     * @param modifyUser the value for vip_student_professional_attach.modify_user
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_student_professional_attach.version
     *
     * @return the value of vip_student_professional_attach.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_student_professional_attach.version
     *
     * @param version the value for vip_student_professional_attach.version
     *
     * @mbggenerated Wed Dec 23 15:59:24 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}