package com.moon.vip.application.inspect;

import com.moon.vip.model.inspect.InspectYear;

public interface InspectYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insert(InspectYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int insertSelective(InspectYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    InspectYear selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKeySelective(InspectYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_inspect_year
     *
     * @mbggenerated Wed Dec 23 15:54:17 CST 2015
     */
    int updateByPrimaryKey(InspectYear record);
}