package com.moon.vip.application.sys;

import com.moon.vip.model.sys.EmployeeBase;

public interface EmployeeBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_base
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_base
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(EmployeeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_base
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(EmployeeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_base
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    EmployeeBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_base
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(EmployeeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_employee_base
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(EmployeeBase record);
}