package com.moon.vip.application.sys;

import com.moon.vip.model.sys.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(Role record);
    /**
     * 根据权限Code获取ID
     * @方法名: selectRoleIdByCode   
     * @作用: TODO(这里用一句话描述这个方法的作用)            
     * @日期:2016下午7:10:45
     */
    int selectRoleIdByCode(String roleCode);
}