package com.moon.vip.application.assignment;

import com.moon.vip.model.assignment.SchoolAssignmentWeek;

public interface SchoolAssignmentWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insert(SchoolAssignmentWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insertSelective(SchoolAssignmentWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    SchoolAssignmentWeek selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKeySelective(SchoolAssignmentWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKey(SchoolAssignmentWeek record);
}