package com.moon.vip.application.interviews;

import com.moon.vip.model.interviews.Interviews;

public interface InterviewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_interviews
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_interviews
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    int insert(Interviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_interviews
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    int insertSelective(Interviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_interviews
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    Interviews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_interviews
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    int updateByPrimaryKeySelective(Interviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_interviews
     *
     * @mbggenerated Wed Dec 23 16:00:43 CST 2015
     */
    int updateByPrimaryKey(Interviews record);
}