package com.moon.vip.application.sys;

import com.moon.vip.model.sys.DataRule;

public interface DataRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_data_rule
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_data_rule
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insert(DataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_data_rule
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int insertSelective(DataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_data_rule
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    DataRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_data_rule
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKeySelective(DataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_data_rule
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    int updateByPrimaryKey(DataRule record);
}