package com.moon.vip.model.assignment;

import java.util.Date;

public class SchoolAssignmentWeek {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.ID
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.profession_id
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer professionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.class_id
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.check_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private String checkYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.check_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer checkWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.submit_number
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer submitNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.hiatus_number
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer hiatusNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.create_time
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_school_assignment_week.version
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.ID
     *
     * @return the value of vip_school_assignment_week.ID
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.ID
     *
     * @param id the value for vip_school_assignment_week.ID
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.profession_id
     *
     * @return the value of vip_school_assignment_week.profession_id
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.profession_id
     *
     * @param professionId the value for vip_school_assignment_week.profession_id
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setProfessionId(Integer professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.class_id
     *
     * @return the value of vip_school_assignment_week.class_id
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.class_id
     *
     * @param classId the value for vip_school_assignment_week.class_id
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.check_year
     *
     * @return the value of vip_school_assignment_week.check_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public String getCheckYear() {
        return checkYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.check_year
     *
     * @param checkYear the value for vip_school_assignment_week.check_year
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setCheckYear(String checkYear) {
        this.checkYear = checkYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.check_week
     *
     * @return the value of vip_school_assignment_week.check_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getCheckWeek() {
        return checkWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.check_week
     *
     * @param checkWeek the value for vip_school_assignment_week.check_week
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setCheckWeek(Integer checkWeek) {
        this.checkWeek = checkWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.submit_number
     *
     * @return the value of vip_school_assignment_week.submit_number
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getSubmitNumber() {
        return submitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.submit_number
     *
     * @param submitNumber the value for vip_school_assignment_week.submit_number
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setSubmitNumber(Integer submitNumber) {
        this.submitNumber = submitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.hiatus_number
     *
     * @return the value of vip_school_assignment_week.hiatus_number
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getHiatusNumber() {
        return hiatusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.hiatus_number
     *
     * @param hiatusNumber the value for vip_school_assignment_week.hiatus_number
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setHiatusNumber(Integer hiatusNumber) {
        this.hiatusNumber = hiatusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.create_time
     *
     * @return the value of vip_school_assignment_week.create_time
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.create_time
     *
     * @param createTime the value for vip_school_assignment_week.create_time
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_school_assignment_week.version
     *
     * @return the value of vip_school_assignment_week.version
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_school_assignment_week.version
     *
     * @param version the value for vip_school_assignment_week.version
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}