package com.moon.vip.model.sys;

public class ProfessionSequence extends ProfessionSequenceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_profession_sequence.sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_profession_sequence.version
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_profession_sequence.sequence
     *
     * @return the value of vip_profession_sequence.sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_profession_sequence.sequence
     *
     * @param sequence the value for vip_profession_sequence.sequence
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_profession_sequence.version
     *
     * @return the value of vip_profession_sequence.version
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_profession_sequence.version
     *
     * @param version the value for vip_profession_sequence.version
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}