package com.moon.vip.application.assignment;

import com.moon.vip.model.assignment.SchoolAssignmentDetail;

public interface SchoolAssignmentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_detail
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_detail
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insert(SchoolAssignmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_detail
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int insertSelective(SchoolAssignmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_detail
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    SchoolAssignmentDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_detail
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKeySelective(SchoolAssignmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_school_assignment_detail
     *
     * @mbggenerated Wed Dec 23 15:57:22 CST 2015
     */
    int updateByPrimaryKey(SchoolAssignmentDetail record);
}