package com.moon.vip.model.sys;

import java.util.Date;

public class ActionType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.type_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_action_type.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.ID
     *
     * @return the value of vip_action_type.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.ID
     *
     * @param id the value for vip_action_type.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.type
     *
     * @return the value of vip_action_type.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.type
     *
     * @param type the value for vip_action_type.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.type_name
     *
     * @return the value of vip_action_type.type_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.type_name
     *
     * @param typeName the value for vip_action_type.type_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.is_valid
     *
     * @return the value of vip_action_type.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.is_valid
     *
     * @param isValid the value for vip_action_type.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.create_time
     *
     * @return the value of vip_action_type.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.create_time
     *
     * @param createTime the value for vip_action_type.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.creator
     *
     * @return the value of vip_action_type.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.creator
     *
     * @param creator the value for vip_action_type.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.update_time
     *
     * @return the value of vip_action_type.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.update_time
     *
     * @param updateTime the value for vip_action_type.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.updator
     *
     * @return the value of vip_action_type.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.updator
     *
     * @param updator the value for vip_action_type.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_action_type.version
     *
     * @return the value of vip_action_type.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_action_type.version
     *
     * @param version the value for vip_action_type.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}