package com.moon.vip.model.sys;

import java.util.Date;

public class CodeTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.type_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.code_key
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String codeKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.code_value
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String codeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.code_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer codeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.note
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.modify_user
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_code_table.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.ID
     *
     * @return the value of vip_code_table.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.ID
     *
     * @param id the value for vip_code_table.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.type
     *
     * @return the value of vip_code_table.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.type
     *
     * @param type the value for vip_code_table.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.type_name
     *
     * @return the value of vip_code_table.type_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.type_name
     *
     * @param typeName the value for vip_code_table.type_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.code_key
     *
     * @return the value of vip_code_table.code_key
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCodeKey() {
        return codeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.code_key
     *
     * @param codeKey the value for vip_code_table.code_key
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCodeKey(String codeKey) {
        this.codeKey = codeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.code_value
     *
     * @return the value of vip_code_table.code_value
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.code_value
     *
     * @param codeValue the value for vip_code_table.code_value
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.code_order
     *
     * @return the value of vip_code_table.code_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getCodeOrder() {
        return codeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.code_order
     *
     * @param codeOrder the value for vip_code_table.code_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCodeOrder(Integer codeOrder) {
        this.codeOrder = codeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.is_valid
     *
     * @return the value of vip_code_table.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.is_valid
     *
     * @param isValid the value for vip_code_table.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.note
     *
     * @return the value of vip_code_table.note
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.note
     *
     * @param note the value for vip_code_table.note
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.create_time
     *
     * @return the value of vip_code_table.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.create_time
     *
     * @param createTime the value for vip_code_table.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.creator
     *
     * @return the value of vip_code_table.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.creator
     *
     * @param creator the value for vip_code_table.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.modify_time
     *
     * @return the value of vip_code_table.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.modify_time
     *
     * @param modifyTime the value for vip_code_table.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.modify_user
     *
     * @return the value of vip_code_table.modify_user
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.modify_user
     *
     * @param modifyUser the value for vip_code_table.modify_user
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_code_table.version
     *
     * @return the value of vip_code_table.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_code_table.version
     *
     * @param version the value for vip_code_table.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}