package com.moon.vip.model.sys;

import java.util.Date;

public class DataRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.rule_content
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String ruleContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_data_rule.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.ID
     *
     * @return the value of vip_data_rule.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.ID
     *
     * @param id the value for vip_data_rule.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.name
     *
     * @return the value of vip_data_rule.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.name
     *
     * @param name the value for vip_data_rule.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.rule_content
     *
     * @return the value of vip_data_rule.rule_content
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getRuleContent() {
        return ruleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.rule_content
     *
     * @param ruleContent the value for vip_data_rule.rule_content
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setRuleContent(String ruleContent) {
        this.ruleContent = ruleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.is_valid
     *
     * @return the value of vip_data_rule.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.is_valid
     *
     * @param isValid the value for vip_data_rule.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.create_time
     *
     * @return the value of vip_data_rule.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.create_time
     *
     * @param createTime the value for vip_data_rule.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.creator
     *
     * @return the value of vip_data_rule.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.creator
     *
     * @param creator the value for vip_data_rule.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.update_time
     *
     * @return the value of vip_data_rule.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.update_time
     *
     * @param updateTime the value for vip_data_rule.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.updator
     *
     * @return the value of vip_data_rule.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.updator
     *
     * @param updator the value for vip_data_rule.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_data_rule.version
     *
     * @return the value of vip_data_rule.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_data_rule.version
     *
     * @param version the value for vip_data_rule.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}