package com.moon.vip.model.sys;

import java.util.Date;

public class EmployeeBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.employee_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String employeeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.password
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.nick_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.organization_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.organization_level
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String organizationLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.level_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String levelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.level_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String levelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.superior
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer superior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.superior_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer superiorRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.bank_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.bank_subbranch
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String bankSubbranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.bank_address
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String bankAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.bank_code_number
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String bankCodeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.try_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer trySalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.formal_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer formalSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.current_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer currentSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.entry_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.leave_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date leaveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.effective_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.status
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.initial_post
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer initialPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.initial_org
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer initialOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.account_status
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_employee_base.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.ID
     *
     * @return the value of vip_employee_base.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.ID
     *
     * @param id the value for vip_employee_base.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.employee_code
     *
     * @return the value of vip_employee_base.employee_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.employee_code
     *
     * @param employeeCode the value for vip_employee_base.employee_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.password
     *
     * @return the value of vip_employee_base.password
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.password
     *
     * @param password the value for vip_employee_base.password
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.name
     *
     * @return the value of vip_employee_base.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.name
     *
     * @param name the value for vip_employee_base.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.nick_name
     *
     * @return the value of vip_employee_base.nick_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.nick_name
     *
     * @param nickName the value for vip_employee_base.nick_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.organization_id
     *
     * @return the value of vip_employee_base.organization_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.organization_id
     *
     * @param organizationId the value for vip_employee_base.organization_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.organization_level
     *
     * @return the value of vip_employee_base.organization_level
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getOrganizationLevel() {
        return organizationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.organization_level
     *
     * @param organizationLevel the value for vip_employee_base.organization_level
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setOrganizationLevel(String organizationLevel) {
        this.organizationLevel = organizationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.level_type
     *
     * @return the value of vip_employee_base.level_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.level_type
     *
     * @param levelType the value for vip_employee_base.level_type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setLevelType(String levelType) {
        this.levelType = levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.level_code
     *
     * @return the value of vip_employee_base.level_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.level_code
     *
     * @param levelCode the value for vip_employee_base.level_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.superior
     *
     * @return the value of vip_employee_base.superior
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.superior
     *
     * @param superior the value for vip_employee_base.superior
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setSuperior(Integer superior) {
        this.superior = superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.superior_role
     *
     * @return the value of vip_employee_base.superior_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getSuperiorRole() {
        return superiorRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.superior_role
     *
     * @param superiorRole the value for vip_employee_base.superior_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setSuperiorRole(Integer superiorRole) {
        this.superiorRole = superiorRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.bank_code
     *
     * @return the value of vip_employee_base.bank_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.bank_code
     *
     * @param bankCode the value for vip_employee_base.bank_code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.bank_subbranch
     *
     * @return the value of vip_employee_base.bank_subbranch
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getBankSubbranch() {
        return bankSubbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.bank_subbranch
     *
     * @param bankSubbranch the value for vip_employee_base.bank_subbranch
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setBankSubbranch(String bankSubbranch) {
        this.bankSubbranch = bankSubbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.bank_address
     *
     * @return the value of vip_employee_base.bank_address
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.bank_address
     *
     * @param bankAddress the value for vip_employee_base.bank_address
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.bank_code_number
     *
     * @return the value of vip_employee_base.bank_code_number
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getBankCodeNumber() {
        return bankCodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.bank_code_number
     *
     * @param bankCodeNumber the value for vip_employee_base.bank_code_number
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setBankCodeNumber(String bankCodeNumber) {
        this.bankCodeNumber = bankCodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.try_salary
     *
     * @return the value of vip_employee_base.try_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getTrySalary() {
        return trySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.try_salary
     *
     * @param trySalary the value for vip_employee_base.try_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setTrySalary(Integer trySalary) {
        this.trySalary = trySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.formal_salary
     *
     * @return the value of vip_employee_base.formal_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getFormalSalary() {
        return formalSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.formal_salary
     *
     * @param formalSalary the value for vip_employee_base.formal_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setFormalSalary(Integer formalSalary) {
        this.formalSalary = formalSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.current_salary
     *
     * @return the value of vip_employee_base.current_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getCurrentSalary() {
        return currentSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.current_salary
     *
     * @param currentSalary the value for vip_employee_base.current_salary
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCurrentSalary(Integer currentSalary) {
        this.currentSalary = currentSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.entry_time
     *
     * @return the value of vip_employee_base.entry_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.entry_time
     *
     * @param entryTime the value for vip_employee_base.entry_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.leave_time
     *
     * @return the value of vip_employee_base.leave_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.leave_time
     *
     * @param leaveTime the value for vip_employee_base.leave_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setLeaveTime(Date leaveTime) {
        this.leaveTime = leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.effective_time
     *
     * @return the value of vip_employee_base.effective_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.effective_time
     *
     * @param effectiveTime the value for vip_employee_base.effective_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.status
     *
     * @return the value of vip_employee_base.status
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.status
     *
     * @param status the value for vip_employee_base.status
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.initial_post
     *
     * @return the value of vip_employee_base.initial_post
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getInitialPost() {
        return initialPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.initial_post
     *
     * @param initialPost the value for vip_employee_base.initial_post
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setInitialPost(Integer initialPost) {
        this.initialPost = initialPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.initial_org
     *
     * @return the value of vip_employee_base.initial_org
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getInitialOrg() {
        return initialOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.initial_org
     *
     * @param initialOrg the value for vip_employee_base.initial_org
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setInitialOrg(Integer initialOrg) {
        this.initialOrg = initialOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.account_status
     *
     * @return the value of vip_employee_base.account_status
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.account_status
     *
     * @param accountStatus the value for vip_employee_base.account_status
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.create_time
     *
     * @return the value of vip_employee_base.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.create_time
     *
     * @param createTime the value for vip_employee_base.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.creator
     *
     * @return the value of vip_employee_base.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.creator
     *
     * @param creator the value for vip_employee_base.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.update_time
     *
     * @return the value of vip_employee_base.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.update_time
     *
     * @param updateTime the value for vip_employee_base.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.updator
     *
     * @return the value of vip_employee_base.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.updator
     *
     * @param updator the value for vip_employee_base.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_employee_base.version
     *
     * @return the value of vip_employee_base.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_employee_base.version
     *
     * @param version the value for vip_employee_base.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	@Override
	public String toString() {
		return "EmployeeBase [id=" + id + ", employeeCode=" + employeeCode + ", password=" + password + ", name="
				+ name + ", nickName=" + nickName + ", organizationId=" + organizationId + ", organizationLevel="
				+ organizationLevel + ", levelType=" + levelType + ", levelCode=" + levelCode + ", superior="
				+ superior + ", superiorRole=" + superiorRole + ", bankCode=" + bankCode + ", bankSubbranch="
				+ bankSubbranch + ", bankAddress=" + bankAddress + ", bankCodeNumber=" + bankCodeNumber
				+ ", trySalary=" + trySalary + ", formalSalary=" + formalSalary + ", currentSalary=" + currentSalary
				+ ", entryTime=" + entryTime + ", leaveTime=" + leaveTime + ", effectiveTime=" + effectiveTime
				+ ", status=" + status + ", initialPost=" + initialPost + ", initialOrg=" + initialOrg
				+ ", accountStatus=" + accountStatus + ", createTime=" + createTime + ", creator=" + creator
				+ ", updateTime=" + updateTime + ", updator=" + updator + ", version=" + version + "]";
	}
}