package com.moon.vip.model.sys;

import java.util.Date;

public class MenuResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.url
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.append
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String append;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.class_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.menu_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.menu_lable_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String menuLableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.parent_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_menu_resource.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.ID
     *
     * @return the value of vip_menu_resource.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.ID
     *
     * @param id the value for vip_menu_resource.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.type
     *
     * @return the value of vip_menu_resource.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.type
     *
     * @param type the value for vip_menu_resource.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.url
     *
     * @return the value of vip_menu_resource.url
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.url
     *
     * @param url the value for vip_menu_resource.url
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.name
     *
     * @return the value of vip_menu_resource.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.name
     *
     * @param name the value for vip_menu_resource.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.append
     *
     * @return the value of vip_menu_resource.append
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getAppend() {
        return append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.append
     *
     * @param append the value for vip_menu_resource.append
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setAppend(String append) {
        this.append = append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.class_name
     *
     * @return the value of vip_menu_resource.class_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.class_name
     *
     * @param className the value for vip_menu_resource.class_name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.menu_order
     *
     * @return the value of vip_menu_resource.menu_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.menu_order
     *
     * @param menuOrder the value for vip_menu_resource.menu_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.menu_lable_id
     *
     * @return the value of vip_menu_resource.menu_lable_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getMenuLableId() {
        return menuLableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.menu_lable_id
     *
     * @param menuLableId the value for vip_menu_resource.menu_lable_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setMenuLableId(String menuLableId) {
        this.menuLableId = menuLableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.parent_id
     *
     * @return the value of vip_menu_resource.parent_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.parent_id
     *
     * @param parentId the value for vip_menu_resource.parent_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.is_valid
     *
     * @return the value of vip_menu_resource.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.is_valid
     *
     * @param isValid the value for vip_menu_resource.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.create_time
     *
     * @return the value of vip_menu_resource.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.create_time
     *
     * @param createTime the value for vip_menu_resource.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.creator
     *
     * @return the value of vip_menu_resource.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.creator
     *
     * @param creator the value for vip_menu_resource.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.update_time
     *
     * @return the value of vip_menu_resource.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.update_time
     *
     * @param updateTime the value for vip_menu_resource.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.updator
     *
     * @return the value of vip_menu_resource.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.updator
     *
     * @param updator the value for vip_menu_resource.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_menu_resource.version
     *
     * @return the value of vip_menu_resource.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_menu_resource.version
     *
     * @param version the value for vip_menu_resource.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}