package com.moon.vip.model.sys;

import java.util.Date;

public class OrganizationalProfessional {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.partent_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer partentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.parent_manage_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer parentManageRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.level
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.organizate_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer organizateOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.start_date
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.end_date
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.is_end
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.modfiy_person
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String modifyUser;

    public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifyUser() {
		return modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_organizational_professional.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.ID
     *
     * @return the value of vip_organizational_professional.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.ID
     *
     * @param id the value for vip_organizational_professional.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.type
     *
     * @return the value of vip_organizational_professional.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.type
     *
     * @param type the value for vip_organizational_professional.type
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.name
     *
     * @return the value of vip_organizational_professional.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.name
     *
     * @param name the value for vip_organizational_professional.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.partent_id
     *
     * @return the value of vip_organizational_professional.partent_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getPartentId() {
        return partentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.partent_id
     *
     * @param partentId the value for vip_organizational_professional.partent_id
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setPartentId(Integer partentId) {
        this.partentId = partentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.parent_manage_role
     *
     * @return the value of vip_organizational_professional.parent_manage_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getParentManageRole() {
        return parentManageRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.parent_manage_role
     *
     * @param parentManageRole the value for vip_organizational_professional.parent_manage_role
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setParentManageRole(Integer parentManageRole) {
        this.parentManageRole = parentManageRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.level
     *
     * @return the value of vip_organizational_professional.level
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.level
     *
     * @param level the value for vip_organizational_professional.level
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.organizate_order
     *
     * @return the value of vip_organizational_professional.organizate_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getOrganizateOrder() {
        return organizateOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.organizate_order
     *
     * @param organizateOrder the value for vip_organizational_professional.organizate_order
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setOrganizateOrder(Integer organizateOrder) {
        this.organizateOrder = organizateOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.is_valid
     *
     * @return the value of vip_organizational_professional.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.is_valid
     *
     * @param isValid the value for vip_organizational_professional.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.start_date
     *
     * @return the value of vip_organizational_professional.start_date
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.start_date
     *
     * @param startDate the value for vip_organizational_professional.start_date
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.end_date
     *
     * @return the value of vip_organizational_professional.end_date
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.end_date
     *
     * @param endDate the value for vip_organizational_professional.end_date
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.is_end
     *
     * @return the value of vip_organizational_professional.is_end
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.is_end
     *
     * @param isEnd the value for vip_organizational_professional.is_end
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsEnd(String isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.create_time
     *
     * @return the value of vip_organizational_professional.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.create_time
     *
     * @param createTime the value for vip_organizational_professional.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.creator
     *
     * @return the value of vip_organizational_professional.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.modify_time
     *
     * @return the value of vip_organizational_professional.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.modify_time
     *
     * @param modifyTime the value for vip_organizational_professional.modify_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_organizational_professional.version
     *
     * @return the value of vip_organizational_professional.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_organizational_professional.version
     *
     * @param version the value for vip_organizational_professional.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}