package com.moon.vip.model.sys;

public class ProfessionSequenceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_profession_sequence.profession_id
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    private Integer professionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_profession_sequence.produce_date
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    private String produceDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_profession_sequence.profession_id
     *
     * @return the value of vip_profession_sequence.profession_id
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public Integer getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_profession_sequence.profession_id
     *
     * @param professionId the value for vip_profession_sequence.profession_id
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public void setProfessionId(Integer professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_profession_sequence.produce_date
     *
     * @return the value of vip_profession_sequence.produce_date
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public String getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_profession_sequence.produce_date
     *
     * @param produceDate the value for vip_profession_sequence.produce_date
     *
     * @mbggenerated Tue Jan 19 18:24:10 CST 2016
     */
    public void setProduceDate(String produceDate) {
        this.produceDate = produceDate;
    }
}