package com.moon.vip.model.sys;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.description
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_role.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.ID
     *
     * @return the value of vip_role.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.ID
     *
     * @param id the value for vip_role.ID
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.name
     *
     * @return the value of vip_role.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.name
     *
     * @param name the value for vip_role.name
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.code
     *
     * @return the value of vip_role.code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.code
     *
     * @param code the value for vip_role.code
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.description
     *
     * @return the value of vip_role.description
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.description
     *
     * @param description the value for vip_role.description
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.is_valid
     *
     * @return the value of vip_role.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.is_valid
     *
     * @param isValid the value for vip_role.is_valid
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.create_time
     *
     * @return the value of vip_role.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.create_time
     *
     * @param createTime the value for vip_role.create_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.creator
     *
     * @return the value of vip_role.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.creator
     *
     * @param creator the value for vip_role.creator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.update_time
     *
     * @return the value of vip_role.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.update_time
     *
     * @param updateTime the value for vip_role.update_time
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.updator
     *
     * @return the value of vip_role.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.updator
     *
     * @param updator the value for vip_role.updator
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_role.version
     *
     * @return the value of vip_role.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_role.version
     *
     * @param version the value for vip_role.version
     *
     * @mbggenerated Wed Dec 23 15:44:50 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	@Override
	public String toString() {
		return "Role [id=" + id + ", name=" + name + ", code=" + code + ", description=" + description + ", isValid="
				+ isValid + ", createTime=" + createTime + ", creator=" + creator + ", updateTime=" + updateTime
				+ ", updator=" + updator + ", version=" + version + "]";
	}
}